---

- hosts: all
  become: true

  pre_tasks:
    - name: install updates (RHEL)
      dnf:
        update_only: yes      # 1
        update_cache: yes     # 2
      when: ansible_distribution == "AlmaLinux"

    - name: install update (Ubuntu)
      apt:
        upgrade: dist         # 3
        update_cache: yes     # 4
      when: ansible_distribution == "Ubuntu"


- hosts: web_servers
  become: true

  tasks:
    - name: install pass and w3m for ubuntu servers
      apt:
        name:
          - pass
          - w3m
        state: present
          # update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: install apache and php for RHEL servers
      dnf:
        name:
          - pass
          - w3m
        state: present
          # update_cache: yes
      when: ansible_distribution == "AlmaLinux"

- hosts: db_servers
  become: true
  
  tasks:
    - name: install mariadb package (AlmaLinux)
      dnf:
        name: mariadb
        state: latest
      when: ansible_distribution == "AlmaLinux"

    - name: install mariadb package (Ubuntu)
      apt:
        name: mariadb-server
        state: latest
      when: ansible_distribution == "Ubuntu"

- hosts: file_servers
  become: true

  tasks:
    - name: install samba package
      package:          # 4
        name: samba
        state: latest

