---

- hosts: all
# ansible all veya ansible-playbook all
  become: true
# ansible --become    sudo ile aynı
  tasks:

  - name: install pass and w3m  package
    package:
      name: 
        - "{{ pass_package}}"
        - "{{ w3m_package }}"
      state: present
      update_cache: yes

